<#import "layout.ftlh" as main>

<@main.layout>

    <div class="card">

        <h1>
            MoneyTransferApp
        </h1>

        <p>
            Электронный кошелек для переводов
            и оплаты услуг.
        </p>


        <a
                href="/login"
                class="btn"
        >
            Войти
        </a>


        <a
                href="/register"
                class="btn"
        >
            Регистрация
        </a>

    </div>

</@main.layout>